### ISSUE TITLE
this is great

### ISSUE THREAD

**Issue by johnxie** [togakangaroo/estimation-checklist#2]
Is it possible we can turn this into a template on www.taskade.com/templates?
We will credit the github repo in it.

**Comment by togakangaroo** [comment]
Absolutely @johnxie please do. Like the README says,

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Estimation Checklist</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
